<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>XBee</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>.NET Standard library for controlling XBee wireless modules.</Description>
    <Version>2.0.0</Version>
    <PackageReleaseNotes>Updated to .NET 8</PackageReleaseNotes>
    <PackageTags>XBee Wireless</PackageTags>
    <Authors>Jeff Haynes</Authors>
    <Company />
    <PackageProjectUrl>https://github.com/jefffhaynes/XBee</PackageProjectUrl>
    <RepositoryUrl>https://github.com/jefffhaynes/XBee</RepositoryUrl>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <FileVersion>2.0.0</FileVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>xbcs.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BinarySerializer" Version="8.6.4.1" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.2.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\xbcs.png">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
  </ItemGroup>
</Project>