<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\xbcs.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Runtime" />
    <Reference Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\XBee.Core\XBee.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
  <PropertyGroup>
    <AssemblyTitle>XBee.Classic</AssemblyTitle>
    <Description>A .NET library for controlling XBee wireless modules.</Description>
    <Product>XBee.Classic</Product>
    <AssemblyVersion>5.3.3.0</AssemblyVersion>
    <FileVersion>5.3.3.0</FileVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/jefffhaynes/XBee</PackageProjectUrl>
    <PackageIcon>xbcs.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/jefffhaynes/XBee</RepositoryUrl>
    <PackageTags>XBee Wireless</PackageTags>
    <PackageReleaseNotes>Initial release of .NET only (no UWP)</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>